# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: panini 1.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "panini".freeze
  s.version = "1.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["mjbellantoni".freeze]
  s.date = "2017-03-26"
  s.description = "Panini allows you to generate sentences from a context-free grammar, also known as a CFG.".freeze
  s.email = "mjbellantoni@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "examples/arithmetic_expression.rb",
    "lib/derivation_strategy/base.rb",
    "lib/derivation_strategy/exhaustive.rb",
    "lib/derivation_strategy/leftmost.rb",
    "lib/derivation_strategy/random_dampened.rb",
    "lib/grammar.rb",
    "lib/hash.rb",
    "lib/nonterminal.rb",
    "lib/panini.rb",
    "panini.gemspec",
    "spec/derivation_strategy/dampened_probability_production_choice_proxy_spec.rb",
    "spec/derivation_strategy/exhaustive_spec.rb",
    "spec/derivation_strategy/leftmost_spec.rb",
    "spec/derivation_strategy/random_dampened_spec.rb",
    "spec/grammar_spec.rb",
    "spec/nonterminal_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/basic_derivation_strategy_shared_example.rb"
  ]
  s.homepage = "http://github.com/mjbellantoni/panini".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.10".freeze
  s.summary = "Create sentences from a context-free grammar (CFG)".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_development_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
    else
      s.add_dependency(%q<rspec>.freeze, [">= 0"])
      s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>.freeze, [">= 0"])
    s.add_dependency(%q<bundler>.freeze, ["~> 1.0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
  end
end

